name: Blog Posts

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: install hugo
        run: |
          sudo apt-get update -y
          sudo apt-get install hugo -y

      - name: checkout blog repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          submodules: true
          path: blog

      - name: checkout prakashblogs repo
        uses: actions/checkout@v3
        with:
          repository: prakashblogs/prakashblogs.github.io
          path: prakashblogs.github.io

      - name: generate hugo site
        run: |
          ls -R
          cd blog/myblog
          hugo -t hugo-theme-texify -d ../../blog

      # - name: change dir for prakashblogs
      #   run: |
      #     mkdir prakashblogs
      #     cd prakashblogs


      # - name: delete blog folder from prakashblogs
      #   run: |
      #     pwd
      #     ls
      #     rm -rf blog
      #     echo "blog folder deleted "
      #     cp myblog/public prakashblogs/blog
      #     echo "copied"
      
      - name: commit and push prakashblogs to remote
        run: |
          ls -R
          git config user.name rpeb
          git config user.email prakashdubey1999@gmail.com
          cd prakashblogs.github.io
          git add .
          git commit -m "blog added"
          git push

