name: Blog Posts

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: install hugo
        run: |
          sudo apt-get update -y
          sudo apt-get install hugo -y

      - name: checkout blog repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          submodules: true
          path: blog

      - name: checkout prakashblogs repo
        uses: actions/checkout@v3
        with:
          repository: prakashblogs/prakashblogs.github.io
          path: prakashblogs.github.io

      - name: generate hugo site
        run: |
          cd blog/myblog
          hugo -t hugo-theme-texify -d ../../prakashblogs.github.io/blog
        
      - name: push to prakashblogs repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'prakashblogs.github.io'
          destination-github-username: 'prakashblogs'
          destination-repository-name: 'prakashblogs.github.io'
          user-email: prakashdubey1999@gmail.com
          target-branch: main

